//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipotesi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sintomi
    {
        public string Codice { get; set; }
        public string Apparato { get; set; }
        public string ValorePatologico { get; set; }
        public string Sintomo { get; set; }
        public string Numeri { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
